import argparse
import yaml
import os
import xml.etree.ElementTree as ET
import datetime

# --- 1. CONFIGURATION LOADING ---
def load_mappings(file_path):
    """Loads the service-to-module mappings from the YAML file."""
    if not os.path.exists(file_path):
        print(f"❌ Error: Mappings file not found at {file_path}")
        return None
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            return yaml.safe_load(f)
    except yaml.YAMLError as e:
        print(f"❌ Error loading YAML mappings: {e}")
        return None

# --- 2. ARGUMENT PARSING ---
def parse_arguments():
    """Handles command-line arguments for the script."""
    parser = argparse.ArgumentParser(
        description="Converts Nmap XML output to a Metasploit resource script (.rc) for safe enumeration."
    )
    # Required argument for Nmap XML file
    parser.add_argument(
        "nmap_xml_file",
        help="Path to the Nmap XML output file (-oX format)."
    )
    # Optional flag for dry-run mode
    parser.add_argument(
        "-d", "--dry-run",
        action="store_true",
        help="Lists planned modules without generating the .rc file."
    )
    # Optional argument for thread count
    parser.add_argument(
        "-t", "--threads",
        type=int,
        default=10,
        help="Set the THREADS option for Metasploit modules (default: 10)."
    )
    
    return parser.parse_args()

# --- 3. XML PARSING ---
def parse_nmap_xml(xml_file_path):
    """Parses the Nmap XML file to extract host IPs and open services."""
    hosts_data = {}
    try:
        tree = ET.parse(xml_file_path)
        root = tree.getroot()
    except Exception as e:
        print(f"❌ Error parsing XML file {xml_file_path}: {e}")
        return hosts_data

    for host in root.findall('host'):
        ip_address = None
        for address_element in host.findall('address'):
            if address_element.get('addrtype') == 'ipv4':
                ip_address = address_element.get('addr')
                break
        
        if ip_address is None:
            continue

        status_element = host.find('status')
        if status_element is not None and status_element.get('state') != 'up':
            continue

        open_services = []
        for port in host.findall('./ports/port'):
            state = port.find('state')
            if state is not None and state.get('state') == 'open':
                port_id = port.get('portid')
                protocol = port.get('protocol')
                service_element = port.find('service')
                service_name = service_element.get('name', 'unknown').lower()
                open_services.append((port_id, service_name, protocol))

        if open_services:
            hosts_data[ip_address] = open_services
            
    return hosts_data

# --- 4. RC SCRIPT GENERATION (FINAL VERSION) ---
def generate_rc_script(hosts_data, mappings, args):
    """Matches parsed Nmap services to Metasploit modules and generates the .rc script content."""
    rc_script_lines = []
    
    # Header setup
    workspace_name = os.path.splitext(os.path.basename(args.nmap_xml_file))[0].replace('.', '_').replace('-', '_')
    rc_script_lines.append(f"#!/bin/bash")
    rc_script_lines.append(f"# Metasploit Resource Script generated by NmapToMetasploit.py on {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    rc_script_lines.append(f"\nworkspace -a {workspace_name}")
    rc_script_lines.append(f"db_import {args.nmap_xml_file}\n")
    
    total_modules_planned = 0
    
    for ip, services in hosts_data.items():
        rc_script_lines.append(f"set RHOSTS {ip}")
        
        for port, service_name, protocol in services:
            # Service mapping logic (FIXED: Handles microsoft-ds and http/https to map keys)
            mapping_key = service_name
            if 'smb' in service_name or 'microsoft-ds' in service_name:
                mapping_key = 'smb'
            elif 'http' in service_name or 'ssl' in service_name or 'https' in service_name:
                mapping_key = 'http'

            if mapping_key in mappings:
                service_mapping = mappings[mapping_key]
                rc_script_lines.append(f"set RPORT {port}")
                rc_script_lines.append(f"set PROT {protocol.upper()}")

                rc_script_lines.append(f"# --- Modules for {mapping_key.upper()} on port {port}/{protocol} ---")
                
                for module in service_mapping['modules']:
                    module_name = module['name']
                    description = module.get('description', 'Enumeration module.')

                    rc_script_lines.append(f"use {module_name}")
                    rc_script_lines.append(f"set THREADS {args.threads}") 
                    
                    for opt_name, opt_value in module.get('options', {}).items():
                        rc_script_lines.append(f"set {opt_name} {opt_value}")

                    rc_script_lines.append(f"run -j")
                    rc_script_lines.append(f"# Description: {description}")
                    total_modules_planned += 1
                
                rc_script_lines.append("unset RPORT") 
                rc_script_lines.append("\n")
        
        rc_script_lines.append("unset RHOSTS")
        rc_script_lines.append("services -r\n")

    
    print(f"\n--- Script Generation Complete ---")
    print(f"Total modules planned for run: {total_modules_planned}")
    
    # 5. Output to File or Dry-Run Print
    output_rc_file = f"{workspace_name}_enum.rc"

    if args.dry_run:
        print("\nDry-Run Mode Enabled. Planned script content:")
        print("--------------------------------------------------")
        print("\n".join(rc_script_lines))
        print("--------------------------------------------------")
    else:
        # THIS IS THE FILE WRITING BLOCK THAT WAS PREVIOUSLY MISSING
        try:
            with open(output_rc_file, 'w', encoding='utf-8') as f:
                f.write("\n".join(rc_script_lines))
            print(f"\n✅ SUCCESS: Metasploit Resource Script saved to: {os.path.abspath(output_rc_file)}")
            print(f"To run in msfconsole: resource {output_rc_file}")
        except IOError as e:
            print(f"❌ Error writing to file {output_rc_file}: {e}")
    
    # 5. Output to File or Dry-Run Print
    output_rc_file = f"{workspace_name}_enum.rc"

    if args.dry_run:
        print("\nDry-Run Mode Enabled. Planned script content:")
        print("--------------------------------------------------")
        print("\n".join(rc_script_lines))
        print("--------------------------------------------------")
    else:
        # THIS IS THE FILE WRITING BLOCK
        try:
            with open(output_rc_file, 'w', encoding='utf-8') as f:
                f.write("\n".join(rc_script_lines))
            print(f"\n✅ SUCCESS: Metasploit Resource Script saved to: {os.path.abspath(output_rc_file)}")
            print(f"To run in msfconsole: resource {output_rc_file}")
        except IOError as e:
            print(f"❌ Error writing to file {output_rc_file}: {e}")

# --- MAIN EXECUTION BLOCK ---
def main():
    args = parse_arguments()
    MAPPINGS = load_mappings("mappings.yaml")
    
    if MAPPINGS is None:
        return

    if not os.path.exists(args.nmap_xml_file):
        print(f"❌ Fatal Error: Nmap XML input file not found at {args.nmap_xml_file}.")
        return

    hosts_data = parse_nmap_xml(args.nmap_xml_file)
    
    if not hosts_data:
        print(f"Warning: No 'up' hosts or open services found in {args.nmap_xml_file}. Exiting.")
        return

    print(f"Configuration loaded from mappings.yaml. Found {len(hosts_data)} hosts.")
    print(f"Dry-Run Mode: {'ENABLED' if args.dry_run else 'DISABLED'}")
    
    # Calls the new, fixed generation function
    generate_rc_script(hosts_data, MAPPINGS, args)

if __name__ == "__main__":
    main()